
spring:
  application:
    name: blog-application

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    jwt:
      secret: secret_key
      expiration: 3600000

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

post:
  retention:
    period: 1 # Retention period in days

#logging:
#  level:
#    org:
#      springframework:
#        cache: DEBUG
#        data:
#          redis: DEBUG
#    com:
#      tedsaasfaha: DEBUG